generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        first_name: {label: Nombre}
        last_name: {label: Apellido}
        username: {label: Usuario}
        is_active: {label: Activo}
        email_address: {label: Correo}
        created_at: {label: Fecha creación}
        updated_at: {label: Ultima modificación}
        last_login: {label: Ultimo ingreso}
        action: {label: Acción}
      list:    
        title: Lista de usuarios
        display: [=username, created_at, updated_at, last_login]
      filter:  []
      form:    
        
      edit:    ~
      new:
        title: Agregar usuario
