<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/25 10:39:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=alfaomega',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
